### ISSUE TITLE
Error with turn marker.

### ISSUE THREAD

**Issue by west1778** [Kreals/TurnMarker#2]
![image](https://user-images.githubusercontent.com/73608023/100557468-71ff8400-3277-11eb-8eef-2d8551a8a8f1.png)

Getting this error message.

**Comment by Kreals** [comment]
Yup i've noticed this error, it seems to happen with new worlds. I will test for it soon. if you have any further info it would help.

**Comment by west1778** [comment]
Just let me know what I can get you and I'll try my best lol not really too hip on figuring out the code part of Foundry. :-/

**Comment by Kreals** [comment]
if you could see it happens when you creat a new world or if it happens when you create a new scene it would narrow things down. if not dont worry, i will test for it eventually.

**Comment by west1778** [comment]
![image](https://user-images.githubusercontent.com/73608023/100560281-5601df80-3283-11eb-8c7b-1357ad4ae916.png)
This was from a new scene

**Comment by west1778** [comment]
Sec and I'll try a new world

**Comment by west1778** [comment]
![image](https://user-images.githubusercontent.com/73608023/100560427-c446a200-3283-11eb-8f50-c17b060e153d.png)

This is a fresh world with no other modules running.

**Comment by west1778** [comment]
![image](https://user-images.githubusercontent.com/73608023/100560450-d294be00-3283-11eb-9790-8e97d68b0aad.png)

**Comment by Kreals** [comment]
yeah it seems to fix when you ctrl+f5 refresh on the current scene. thank you.

**Comment by west1778** [comment]
Yeah that seems to make it work weird well I'll use that trick till you get it sorted thanks for replying.

**Comment by Kreals** [comment]
no worries i'll message here when i've squashed it.

**Comment by west1778** [comment]
Thanks a ton.

**Comment by Kreals** [comment]
ok i think i fixed it. will drop a new release shortly. If it crops up again let me know.

**Comment by west1778** [comment]
Well that was fast lol will do :D thanks a lot.

**Comment by Kreals** [comment]
haha ^_^.

**Comment by west1778** [comment]
Ok so the ring comes up on the start of combat now but the turn maker doesn't move through the combatants unless you do the control + F5. :-/ But not seeing any console error it's weird.

**Comment by Kreals** [comment]
just to confirm this only happens when creating a new world and then a new scene? or on a new scene?

**Comment by west1778** [comment]
Didn't test the new scene just put some enemies down and added them to the combat tracker and it made the turn marker like normal but wouldn't move. I'm at work but I can try the new scene new world thing when I get off work

**Comment by Kreals** [comment]
no worries just trying to reproduce it, seems fine on my end but perhaps there is some weird edge case i've missed.

**Comment by west1778** [comment]
Well I do have a lot of modules lol so it's likely something on my end lol
