### ISSUE TITLE
There is a Bug with the recent update

### ISSUE THREAD

**Issue by Flintwyrm** [Kreals/TurnMarker#3]
This error keeps popping up

![Screenshot_578](https://user-images.githubusercontent.com/60701064/100804809-7f457b80-33fb-11eb-8871-03f5fc51e13f.png)
![Screenshot_579](https://user-images.githubusercontent.com/60701064/100804810-7f457b80-33fb-11eb-9154-c19dd1af0cd3.png)

**Comment by Kreals** [comment]
seems to be related to switching scenes with an active combat with no combatents. Think i've found a fix. I will release it shortly. Is it causing any game breaking situations?

**Comment by Flintwyrm** [comment]
it was not at all. I just happened to be looking at my console and saw those errors. which I didnt see the day before

**Comment by Kreals** [comment]
shiny, thanks for letting me know. I'm pretty sure this issue should be resolved, so i'll close it for now. If anything else pops up feel free to raise an issue.
