### ISSUE TITLE
Image doesnt show up/Chat message doesnt show up.

### ISSUE THREAD

**Issue by Flintwyrm** [Kreals/TurnMarker#4]
I updated and Turn marker doesnt do anything that it is supposed to do. not marker underneath actors and no chat message when a new turn comes up.

**Comment by Flintwyrm** [comment]
After some searching I figured out that if the game doesnt have an initiative system it doesnt work. this didnt use to be a problem. buy it seems if I set every one to 1 it will work again.

**Comment by Kreals** [comment]
Yeah I changed it so the marker wouldn't show up until the combat had actually begun and initiatives had been roled. hmm i'll see if there is a way to automatically determine if the system uses initiative and switch logic acordingly. Or maybe just re-write the whole thing again :p. This fix might take a little while though.

also, if this is really bugging anyone i would suggest using v2.6.31 for now. The zip file can be found in the packages directory on github.

- download it [here](https://github.com/Kreals/TurnMarker/raw/main/package/turnmarker-v2.6.31.zip)
- go to '<foundry_user_data>/modules'
- delete the turnmarker directory if it exists
- extract the turnmarker.zip-v2.6.31 to '<foundry_user_data>/modules'
- It should work.

**Comment by Kreals** [comment]
can I ask which game system you are using so i can reproduce this?

**Comment by Flintwyrm** [comment]
Lancer VTT

**Comment by Kreals** [comment]
awesome, thanks.

**Comment by Kreals** [comment]
Should be fixed in v2.7.8.
