### ISSUE TITLE
Leftover Images

### ISSUE THREAD

**Issue by Flintwyrm** [Kreals/TurnMarker#5]
I updated and had turn marker off. I think there was a combat open when this happened but when I ended the combat it stayed like this. Even with the module off. I checked the console and see no errors. is there a command I can put in the console to remove these?
![Screenshot_677](https://user-images.githubusercontent.com/60701064/101693924-5303ad80-3a40-11eb-9343-f7b0a3edcefb.png)

**Comment by Kreals** [comment]
there is a function in the code base that does this. I'll figure out how to expose it so it can be used as a macro. Eventually i'll make this a button in the settings or something. To busy to fix it atm. Should be able to delete the tiles manually. Bit of a pain i know.

**Comment by Flintwyrm** [comment]
I dont mind deleting them manually. I didnt know you could. so that is awesome.

**Comment by Kreals** [comment]
ok this should be sorted for now. If you create a macro with:

`game.turnmarker.tms.clearAllMarkers()`

It should delete all instances of all markers across all scenes.

thanks for the feedback.
