### ISSUE TITLE
Markers are off center on hex grids

### ISSUE THREAD

**Issue by BoltsJ** [Kreals/TurnMarker#6]
When using hex grids, the markers are off center. They are centered according to the long hex axis, but on the short axis they are shifted a bit.
![image](https://user-images.githubusercontent.com/182554/101698703-97427e00-3a3f-11eb-9fbc-a9af01942af1.png)
![image](https://user-images.githubusercontent.com/182554/101698765-b17c5c00-3a3f-11eb-9a02-25f94fb1ce40.png)

The the shifting is consisted on both hex row and column grid types.

![image](https://user-images.githubusercontent.com/182554/101698927-f7392480-3a3f-11eb-9dc8-0c01dca359ee.png)
![image](https://user-images.githubusercontent.com/182554/101698965-01f3b980-3a40-11eb-8081-a580648672e0.png)

**Comment by BoltsJ** [comment]
I am currently working on a patch to fix this. I'll submit it when I finish.

**Comment by Kreals** [comment]
yeah i was aware of this, had plans to fix it soon but i have a bunch of work to finish. If you come up with a fix let me know n i'll add it. If not i'll look into it later.
