### ISSUE TITLE
Animate marker not working

### ISSUE THREAD

**Issue by oestred** [Kreals/TurnMarker#9]
First, I happened to see on the Foundry Discord about your fork of the Turn Marker mod.    Thanks for working to update a helpful module.  It would be great for you to become the official listed Turn Marker mod like I read in the other item.

Anyway, I just installed your latest Turn Marker and started a test encounter.  I noticed the "animate marker" setting was not working.  I unselected it, saved, and reselected the setting and saved but no change.  That setting is a relative minor thing but I wanted to let you know.

**Comment by Kreals** [comment]
awesome, I will check it out and see if i can replicate it and then get back to you.

**Comment by Kreals** [comment]
Hmm seems to be working for me. Is it the settings checkbox state itself not saving or are the actual markers not animating?

**Comment by oestred** [comment]
Hello. I updated to the new version just released of Turn Marker and tried it.  The animation showed as normal this time.  
So it looks like it is good.
  Either something in the update fixed it or maybe another module caused it and that module updated and stopped causing it.

Thank you

**Comment by Kreals** [comment]
Good to hear, if it happens again feel free to re-open this issue.
